# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b6a89e203a0d12d075e169f2af92510f12e48a01a1279e1b767fd0a6bd4da6c686df929c751d74e50b2f3517059ec6905891c958346d36ddef87828e5054396

test:
  secret_key_base: 7ea82f56b066a29eb145b08bb54badf34a15567fefa9678c246f222ff99ed9aea6f06e6884c81fd291a1cccd3128bc815c6810a82ca3e88be908a7c41f7194c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
